### ISSUE TITLE
A discrepancy between the documentation and the implementation

### ISSUE THREAD

**Issue by ShiMeiWo** [felicienfrancois/cordova-plugin-stepper#4]
In the *Note* for `startStepperUpdates(options, onSuccess, onError)`, I found some of discrepancies in the following code example.

```js
stepper.startStepperUpdates(offset, options).then(callback).catch((err) => {
  console.error(err);
});
```

- `stepper.startStepperUpdates(...args)` requires, implementation-wise, the option settings as the first argument and the callback function on success as the second argument, and neither the `offset` nor the `options` can be passed.

- This method does not return a Promise, so then-chaining is not possible.

Thanks!

**Comment by felicienfrancois** [comment]
Thank you for the report.
At some point I was trying to makes it work with promises just like the other endpoints but promises cannot be resolved/rejected multiple time so I rolled back the code, forgetting to rollback par of the documentation.

I just updated documentation to fix the discrepancies.

Please let me know if you find other issues
